6、顺序程序的错误处理
 - Erlang最初被设计用来编写容错式系统
 - “任其崩溃”规则：在Erlang里，防御式编程是内建的，在描述函数的行为时，应该只考虑合法的输入参数，
    其他所有的参数都将导致内部错误并被自动检测到。永远不能让函数对非法的参数返回值，而是应该抛出一个异常错误。
 - 显式生成错误的内置函数：
    - exit(Why)
      当确实想要终止当前进程时使用它，如果这个异常错误没有被捕捉到，信号{'EXIT',Pid,Why}就会被广播给
      当前进程链接的所有进程。
    - throw(Why)
      这个函数的作用是抛出一个调用者可能想要捕捉的异常错误
    - error(Why)
      这个函数的作用是指示“崩溃性错误”，也就是调用者没有准备好处理的非常严重的问题，
      它与系统内部生成的错误差不多
 - 两种捕获异常的方法：
    - 用try...catch表达式将会抛出异常的函数括起来
    - 把函数调用包含在catch表达式里
    try FuncOrExpressionSequence of
        Pattern1 [when Guard1] -> Expression1;
        Pattern2 [when Guard2] -> Expression2;
        ...
    catch
        ExceptionType: ExPattern1 [when ExGuard1] -> ExExpressions1;
        ExceptionType: ExPattern2 [when ExGuard2] -> ExExpressions2;
        ...
    after
        AfterExpressions
    end
    - ExceptionType是原子throw、exit、error中的一个，默认值是throw，
      Erlang运行时系统所检测到的内部错误总是带有error标签。
    - AfterExpressions的返回值会被丢弃。
    - try F
      catch
        ...
      end
      相当于
      try F of
        Val -> Val
      catch
        ...
      end